const students = [
  {
    registrationNumber: "19220101",
    name: "Ali Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A1!Kx7#e",
  },
  {
    registrationNumber: "19220102",
    name: "Sara Ahmed",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S2@hC9&k",
  },
  {
    registrationNumber: "19220103",
    name: "Ahmed Ali",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A3!lI4@m",
  },
  {
    registrationNumber: "19220104",
    name: "Fatima Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "F4@Kp5#w",
  },
  {
    registrationNumber: "19220105",
    name: "Hassan Malik",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "H5!Mx6#s",
  },
  {
    registrationNumber: "19220106",
    name: "Ayesha Rashid",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A6!Rd7@f",
  },
  {
    registrationNumber: "19220107",
    name: "Usman Akhtar",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "U7!Aa8#e",
  },
  {
    registrationNumber: "19220108",
    name: "Mehreen Abbas",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "M8!Aa9#s",
  },
  {
    registrationNumber: "19220109",
    name: "Amir Qureshi",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A9!Qh1#m",
  },
  {
    registrationNumber: "19220110",
    name: "Sadia Raza",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S10!Rz2#a",
  },
  {
    registrationNumber: "19220111",
    name: "Abdullah Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A11!Kb3#m",
  },
  {
    registrationNumber: "19220112",
    name: "Aisha Ahmed",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A12!Ah4#d",
  },
  {
    registrationNumber: "19220113",
    name: "Kamran Ali",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "K13!Al5#n",
  },
  {
    registrationNumber: "19220114",
    name: "Sara Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S14!Kh6#t",
  },
  {
    registrationNumber: "19220115",
    name: "Ahmed Malik",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A15!Ml7#k",
  },
  {
    registrationNumber: "19220116",
    name: "Zainab Rashid",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "Z16!Rd8#h",
  },
  {
    registrationNumber: "19220117",
    name: "Aliya Akhtar",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A17!Aa9#r",
  },
  {
    registrationNumber: "19220118",
    name: "Bilal Abbas",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "B18!Ab0#s",
  },
  {
    registrationNumber: "19220119",
    name: "Ayesha Qureshi",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A19!Qh1#f",
  },
  {
    registrationNumber: "19220120",
    name: "Sadia Raza",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S20!Rz2#a",
  },
  {
    registrationNumber: "19220121",
    name: "Ali Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A21!Kb3#m",
  },
  {
    registrationNumber: "19220122",
    name: "Aisha Ahmed",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A22!Ah4#d",
  },
  {
    registrationNumber: "19220123",
    name: "Kamran Ali",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "K23!Al5#n",
  },
  {
    registrationNumber: "19220124",
    name: "Sara Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S24!Kh6#t",
  },
  {
    registrationNumber: "19220125",
    name: "Ahmed Malik",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A25!Ml7#k",
  },
  {
    registrationNumber: "19220126",
    name: "Zainab Rashid",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "Z26!Rd8#h",
  },
  {
    registrationNumber: "19220127",
    name: "Aliya Akhtar",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A27!Aa9#r",
  },
  {
    registrationNumber: "19220128",
    name: "Bilal Abbas",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "B28!Ab0#s",
  },
  {
    registrationNumber: "19220129",
    name: "Ayesha Qureshi",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A29!Qh1#f",
  },
  {
    registrationNumber: "19220130",
    name: "Sadia Raza",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S30!Rz2#a",
  },
  {
    registrationNumber: "19220131",
    name: "Ali Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A31!Kb3#m",
  },
  {
    registrationNumber: "19220132",
    name: "Aisha Ahmed",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A32!Ah4#d",
  },
  {
    registrationNumber: "19220133",
    name: "Kamran Ali",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "K33!Al5#n",
  },
  {
    registrationNumber: "19220134",
    name: "Sara Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S34!Kh6#t",
  },
  {
    registrationNumber: "19220135",
    name: "Ahmed Malik",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A35!Ml7#k",
  },
  {
    registrationNumber: "19220136",
    name: "Zainab Rashid",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "Z36!Rd8#h",
  },
  {
    registrationNumber: "19220137",
    name: "Aliya Akhtar",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A37!Aa9#r",
  },
  {
    registrationNumber: "19220138",
    name: "Bilal Abbas",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "B38!Ab0#s",
  },
  {
    registrationNumber: "19220139",
    name: "Ayesha Qureshi",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A39!Qh1#f",
  },
  {
    registrationNumber: "19220140",
    name: "Sadia Raza",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S40!Rz2#a",
  },
  {
    registrationNumber: "19220141",
    name: "Ali Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A41!Kb3#m",
  },
  {
    registrationNumber: "19220142",
    name: "Aisha Ahmed",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A42!Ah4#d",
  },
  {
    registrationNumber: "19220143",
    name: "Kamran Ali",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "K43!Al5#n",
  },
  {
    registrationNumber: "19220144",
    name: "Sara Khan",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S44!Kh6#t",
  },
  {
    registrationNumber: "19220145",
    name: "Ahmed Malik",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A45!Ml7#k",
  },
  {
    registrationNumber: "19220146",
    name: "Zainab Rashid",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "Z46!Rd8#h",
  },
  {
    registrationNumber: "19220147",
    name: "Aliya Akhtar",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A47!Aa9#r",
  },
  {
    registrationNumber: "19220148",
    name: "Bilal Abbas",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "B48!Ab0#s",
  },
  {
    registrationNumber: "19220149",
    name: "Ayesha Qureshi",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "A49!Qh1#f",
  },
  {
    registrationNumber: "19220150",
    name: "Sadia Raza",
    Librarian: { status: "Not Requested", liabilityPending: "" },
    ElectronicLab: { status: "Not Requested", liabilityPending: "" },
    ComputerLab: { status: "Not Requested", liabilityPending: "" },
    ProjectCoordinator: { status: "Not Requested", liabilityPending: "" },
    PrintingOffice: { status: "Not Requested", liabilityPending: "" },
    CafeteriaIncharge: { status: "Not Requested", liabilityPending: "" },
    TransportIncharge: { status: "Not Requested", liabilityPending: "" },
    BoysHostel: { status: "Not Requested", liabilityPending: "" },
    AlumniOffice: { status: "Not Requested", liabilityPending: "" },
    KicsitStore: { status: "Not Requested", liabilityPending: "" },
    Accounts: { status: "Not Requested", liabilityPending: "" },
    SportsIncharge: { status: "Not Requested", liabilityPending: "" },
    CardOffice: { status: "Not Requested", liabilityPending: "" },
    HODKicsit: { status: "Not Requested", liabilityPending: "" },
    password: "S50!Rz2#a",
  },
];

export default students;
